# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nutrition' do
  pod: 'Alamofire'
  use_frameworks!

  # Pods for nutrition

  target 'nutritionTests' do
    inherit! :search_paths
  end

  target 'nutritionUITests' do
  end

end
